### ISSUE TITLE
RedisLock throws RedisReadOnlyException when using RedisStaticMasterReplicaConfiguration and ReadFrom.REPLICA_PREFERRED

### ISSUE THREAD

**Issue by mykhailokulakov** [alturkovic/distributed-lock#37]
Hi!
I'm using a master/replica scheme with "read from replica" client property enabled. 
```
var masterReplicaConfiguration =  new RedisStaticMasterReplicaConfiguration(masterNode.getHost(), masterNode.getPort());
redisProperties
    .getReplicas()
    .forEach(
        replica -> {
          RedisNode node = RedisNode.fromString(replica.getHost());
          masterReplicaConfiguration.addNode(node.getHost(), node.getPort());
        });

LettuceClientConfiguration.LettuceClientConfigurationBuilder clientConfigBuilder =
    LettuceClientConfiguration.builder().readFrom(ReadFrom.REPLICA_PREFERRED);
```
It seems that "execute" is treated as a read operation by default, so it throws:

```
c.github.alturkovic.lock.exception.DistributedLockException: Unable to acquire lock with expression: #key
	at com.github.alturkovic.lock.advice.LockMethodInterceptor.executeLockedMethod(LockMethodInterceptor.java:77)
	at com.github.alturkovic.lock.advice.LockMethodInterceptor.invoke(LockMethodInterceptor.java:61)
	... 3 frames excluded
	...
Caused by: <#029e4a23> org.springframework.data.redis.RedisSystemException: Error in execution; nested exception is io.lettuce.core.RedisReadOnlyException: READONLY You can't write against a read only replica. script: 15df23044ffd4f2723d9689555be4a5cccac4154, on @user_script:1.
	at o.s.data.redis.connection.lettuce.LettuceExceptionConverter.convert(LettuceExceptionConverter.java:54)
```

**Comment by alturkovic** [comment]
I don't see any options to flag the operation as `READ_WRITE`, such as with Redissons `RScript.Mode`. At the moment, I don't see a quick fix to do.

I suggest you open an issue with Spring Redis team to expose this option when calling `RedisTemplate.execute`. It seems like it is not exposed properly, unless I am missing something obvious.

In the meanwhile, I would recommend writing your own `Lock` implementation using Redisson and reusing the scripts from `SimpleRedisLock` as a quick fix for your problem. 

Please let me know if you open an issue and what response you get.

**Comment by mykhailokulakov** [comment]
Created an issue 
https://github.com/spring-projects/spring-data-redis/issues/2617
